name: build-release

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: checkout repository
        uses: actions/checkout@v2
      - name: install dependencies
        run: |
          pip install setuptools wheel pyinstaller && \
          pip install -r requirements.txt
      - name: create GraXpert-linux bundle
        run: |
          pyinstaller \
          --icon="./img/Icon.ico" \
          --add-data="./img/*:./img/" \
          --add-data="./forest-dark.tcl:./" \
          --add-data="./forest-dark/*:./forest-dark/" \
          --onefile \
          --hidden-import='PIL._tkinter_finder' \
          --additional-hooks-dir=./releng \
          -n GraXpert-linux \
          ./src/gui.py
      - name: store artifacts
        uses: actions/upload-artifact@v2
        with:
          name: GraXpert-linux
          path: ./dist/GraXpert-linux
          retention-days: 5

  build-windows:
    runs-on: windows-latest
    steps:
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: checkout repository
        uses: actions/checkout@v2
      - name: install dependencies
        run: |
          pip install setuptools wheel pyinstaller && `
          pip install -r requirements.txt
      - name: create GraXpert-win64 bundle
        run: |
          pyinstaller `
          --icon="./img/Icon.ico" `
          --add-data="./img/*;./img/" `
          --add-data="./forest-dark.tcl;./" `
          --add-data="./forest-dark/*;./forest-dark/" `
          --onefile `
          --hidden-import='PIL._tkinter_finder' `
          --additional-hooks-dir=./releng `
          -n GraXpert-win64 `
          ./src/gui.py
      - name: store artifacts
        uses: actions/upload-artifact@v2
        with:
          name: GraXpert-win64.exe
          path: ./dist/GraXpert-win64.exe
          retention-days: 5

  build-macos-x86_64:
    runs-on: macos-10.15
    steps:
      - name: setup python
        run: brew install python-tk@3.9
      - name: checkout repository
        uses: actions/checkout@v2
      - name: install dependencies
        run: |
          pip3 install setuptools wheel pyinstaller && \
          pip3 install -r requirements.txt
      - name: create GraXpert-macos-x86_64 bundle
        run: |
          pyinstaller \
          --icon="./img/Icon.ico" \
          --add-data="./img/*:./img/" \
          --add-data="./forest-dark.tcl:./" \
          --add-data="./forest-dark/*:./forest-dark/" \
          --onefile \
          --hidden-import='PIL._tkinter_finder' \
          --additional-hooks-dir=./releng \
          --target-architecture x86_64 \
          --windowed \
          -n GraXpert-macos-x86_64 \
          ./src/gui.py
      - name: install create-dmg
        run: brew install create-dmg
      - name: create .dmg
        run: |
          create-dmg \
          --volname "GraXpert-macos-x86_64" \
          --window-pos 50 50 \
          --window-size 1920 1080 \
          --icon-size 100 \
          --icon "GraXpert-macos-x86_64.app" 200 190 \
          "dist/GraXpert-macos-x86_64.dmg" \
          "dist/GraXpert-macos-x86_64.app/"
      - name: store artifacts
        uses: actions/upload-artifact@v2
        with:
          name: GraXpert-macos-x86_64.dmg
          path: ./dist/GraXpert-macos-x86_64.dmg
          retention-days: 5

  release:
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows, build-macos-x86_64]
    steps:
      - name: download linux artifacts
        uses: actions/download-artifact@v2
        with:
          name: GraXpert-linux
      - name: download windows artifacts
        uses: actions/download-artifact@v2
        with:
          name: GraXpert-win64.exe
      - name: download macos artifacts
        uses: actions/download-artifact@v2
        with:
          name: GraXpert-macos-x86_64.dmg
      - name: create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: snapshot
          files: |
            GraXpert-linux
            GraXpert-win64.exe
            GraXpert-macos-x86_64.dmg
